service:
  port:
    name: http
    l4_protocol: TCP
    port: 5432
    targetPort: 5432
  label: postgresql-service-1-wmonsbcf8j
  name: postgresql-service-1-wmonsbcf8j
  selector: postgresql-service-1-wmonsbcf8j
  type:
  - ClusterIP
  - NodePort
statefulset:
  name: postgresql-service-1-wmonsbcf8j
  spec:
    name: postgresql-service-1-wmonsbcf8j
    servicename: postgresql-service-1-wmonsbcf8j
  replicas: 1
  container:
    name: postgresql-service-1-wmonsbcf8j
    port: 5432
  volume:
    name: pvc-postgresql-service-1-wmonsbcf8j
  resource:
    request:
      memory: 250Mi
      cpu: 0.25
    limits:
      memory: 0Mi
      cpu: 0
  hpa:
    name: hpa-postgresql-service-1-wmonsbcf8j
    minReplicas: 1
    maxReplicas: 1
    cpu: 70
    memory: -@memAutoScale@-
namespace: dw-app-0610-dev
secret:
  name: 
  registry:
    name: regsecret
    url: turaco-dev-registry.turacocloud.com/dev-turaco-workspace-268/turaco
    username: robot$turaco_common
    password: Zv7beYWhgCQSOUoxZQK1RGWHdvAMltXx
    email: info@twolinecode.com
pvc:
  name: pvc-postgresql-service-1-wmonsbcf8j
  storageClass: tlc-block-sc
  size: 5Gi
  accessMode: ReadWriteOnce
postgres:
  configmap:
    name: config-postgresql-service-1-wmonsbcf8j
  secret:
    name: secret-postgresql-service-1-wmonsbcf8j
    username: admin
    password: "Napp12!"
    root_password: "Napp12!"
    database: postgre
    dbhost: postgresql-service-1-wmonsbcf8j
    port: 5432
  statefulset:
    name: postgresql-service-1-wmonsbcf8j
    image:
      url: registry.turacocloud.com/turaco-common/postgresql-gis:15-3.3
